import type { Metadata } from "next";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import Header from "@/app/components/home/Header";
import Footer from "@/app/components/home/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
      <ClerkProvider>
        <html lang="en">
        <body>
        <Header />
        {children}
        <Footer />
        </body>
        </html>
      </ClerkProvider>
  );
}
